### ISSUE TITLE
localhost resolution appears to be broken

### ISSUE THREAD

**Issue by iJebus** [cunnie/sslip.io#10]
> sslip.io is a DNS server that maps specially-crafted DNS A records to IP addresses (e.g. "127-0-0-1.sslip.io" maps to 127.0.0.1). It is similar to, and inspired by, xip.io.

```sh
$ dig 127-0-0-1.sslip.io

; <<>> DiG 9.10.6 <<>> 127-0-0-1.sslip.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61751
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;127-0-0-1.sslip.io.		IN	A

;; Query time: 84 msec
;; SERVER: x#53(x)
;; WHEN: Wed Sep 29 12:36:41 AWST 2021
;; MSG SIZE  rcvd: 47
```

Other examples appear to be working fine, though.

```sh
$ dig 104.155.144.4.sslip.io

; <<>> DiG 9.10.6 <<>> 104.155.144.4.sslip.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;104.155.144.4.sslip.io.		IN	A

;; ANSWER SECTION:
104.155.144.4.sslip.io.	42834	IN	A	104.155.144.4

;; Query time: 81 msec
;; SERVER: x#53(x)
;; WHEN: Wed Sep 29 12:38:59 AWST 2021
;; MSG SIZE  rcvd: 67
```

**Comment by cunnie** [comment]
Thanks for the catch, @iJebus. Could you do me a favor & tell me **what your upstream DNS** server is  when you get that anomaly? I've checked all my DNS servers and they appear to respond correctly with a query for `127-0-0-1.sslip.io`:

```bash
for NS in $(dig ns sslip.io +short | grep -v ";;"); do echo -n "$NS: "; dig 127-0-0-1.sslip.io @$NS +short; done
```

returns the following:
```
ns-gce.nono.io.: 127.0.0.1
ns-azure.nono.io.: 127.0.0.1
ns-aws.nono.io.: 127.0.0.1
```

Also, when you get the erroneous response, could you please include a timestamp? I can review my logs &  hopefully find what is going on.

**Comment by iJebus** [comment]
Theoretically the router should be forwarding to 9.9.9.9/1.1.1.1, but querying them directly is fine soooooooo 😬 

```sh
$ dig 127-0-0-1.sslip.io @1.1.1.1 +short;
127.0.0.1

$ dig 127-0-0-1.sslip.io @9.9.9.9 +short;
127.0.0.1
```

Running your bash loop I get the following.

```sh
$ date
Wed 29 Sep 2021 17:04:43 AWST

$ for NS in $(dig ns sslip.io +short | grep -v ";;"); do echo -n "$NS: "; dig 127-0-0-1.sslip.io @$NS +short; done
ns-azure.nono.io.: 127.0.0.1
ns-gce.nono.io.: 127.0.0.1
ns-aws.nono.io.:
; <<>> DiG 9.10.6 <<>> 127-0-0-1.sslip.io @ns-aws.nono.io. +short
;; global options: +cmd
;; connection timed out; no servers could be reached
```

All good except AWS, but it's weird that it would be responding fine for you.

Given that it's fine for you maybe there's just something flakey on my side.

**Comment by cunnie** [comment]
Thanks @iJebus , that output is very useful.

**The error you're seeing for `ns-aws` queries was caused by me 2 hours ago**. Specifically, this I uncovered a bug when I reboot the ns-aws server (it only binds to the loopback interface, which renders the nameserver inoperable), but it's unrelated to the initial issue. It's working now.

The initial issue may have been caused by an IPv6 network partition because `ns-aws` is a special nameserver that has both IPv4 & IPv6 addresses. The remaining nameservers are pure IPv4. A simple test:

```bash
ping6 2600:: # IPv6 works
ping6 ns-aws.nono.io # is network partitioned?
dig 127-0-0-1.sslip.io @ns-aws.nono.io -6  +short # let's try the query over IPv6
dig 127-0-0-1.sslip.io @ns-aws.nono.io -4  +short # let's try the query over IPv4 for completeness
```

**Comment by iJebus** [comment]
```sh
$ ping6 2600:: # IPv6 works
ping6 ns-aws.nono.io # is network partitioned?
dig 127-0-0-1.sslip.io @ns-aws.nono.io -6  +short # let's try the query over IPv6
dig 127-0-0-1.sslip.io @ns-aws.nono.io -4  +short # let's try the query over IPv4 for completeness

ping6: UDP connect: No route to host
ping6: UDP connect: No route to host
127.0.0.1
127.0.0.1
```

Looks good. I've noticed with some of the other addresses I've been trying that the first query will fail but trying again a few seconds later. That's normal I'm guessing?

**Comment by cunnie** [comment]
> Looks good. I've noticed with some of the other addresses I've been trying that the first query will fail but trying again a few seconds later. **That's normal I'm guessing**?

No, that's not normal. What's you're experiencing is uncommon, and I'll try to figure out what's happening.

One of the things I can do is modify my continuous integration to test against the 1.1.1.1, 8.8.8.8, and 9.9.9.9 servers to make sure something isn't wrong between my nameservers and those recursive servers.

**Comment by iJebus** [comment]
Just testing again, I notice I'm only seeing that with my internal setup. As in, when I'm not specifying 1.1.1.1 or one of the others. I'm more and more convinced there's something off in my local setup and not an issue with sslip.io so I'll close the issue. Appreciate the time you've taken so far and your very polite manner! 💯

**Comment by cunnie** [comment]
@iJebus I'm glad to hear it's probably not my end. And thanks for raising the issue because it uncovered two unrelated bugs, one of which I already fixed.

**Comment by creydr** [comment]
For others having the same problem: I had the same problem and at the end my configured dns server couldn't resolve sslip.io subdomains:

```
$ dig 127.0.0.1.sslip.io +short

```
whereas it resolved when I used the google dns server: 
```
$ dig hello.default.127.0.0.1.sslip.io @8.8.8.8 +short
127.0.0.1
```

Since I used systemd-resolvd for dns resolution, I ended up adding the google dns servers to my `/etc/systemd/resolved.conf`:

```
...
DNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
...
```
And then restarted the related services:

```
$ sudo systemctl daemon-reload
$ sudo systemctl restart systemd-networkd
$ sudo systemctl restart systemd-resolved
```

**Comment by cunnie** [comment]
Thanks for the tip, @creydr ! If you have the time, I'd be curious to know which DNS servers systemd-resolvd was using before the override was implemented — I'm quite curious if there's a subtle error which I'm not aware of, and I'm looking for clues.

**Comment by creydr** [comment]
It seems my router (AVM fritzbox) with its default settings to be the problem. The pre-configured DNS server from the router (`2001:1438:2:4::8`) works fine and can resolve the sslip.io domains:

```
$ dig 127.0.0.1.sslip.io +short @192.168.178.1
<no response>

$ dig 127.0.0.1.sslip.io +short @2001:1438:2:4::8
127.0.0.1
```

**Comment by momesana** [comment]
@creydr,
your solution worked for me as well. I have the same issue and also utilize a fritzbox router at home.
