### ISSUE TITLE
Local build - is it possible to define a local fake domain name

### ISSUE THREAD

**Issue by JCzz** [cunnie/sslip.io#12]
Hi
Nice tool! I have cloned and build locally - it is possible to define a fake local domain to loop back to 127.0.0.1?

I found a Customizations variable xip.go line 78-79

```
	Customizations      = DomainCustomizations{
		"myfakelocal.io.": {
```

But it does not loop back - is it possible? 
Could be nice to be able to give a domain as a parameter when running sslip.

Thanks

**Comment by cunnie** [comment]
@JCzz — you're using my code? What a pleasant surprise—and a bold move!

You should be set a local loopback with something like the following in the `Customizations` variable:

```go
		"myfakelocal.io.": {
			A:    []dnsmessage.AResource{{A: [4]byte{127, 0, 0, 1}}},
			AAAA: []dnsmessage.AAAAResource{{AAAA: [16]byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}}},
		},

```

Let me know if this doesn't work & I'll dig further.

**Comment by JCzz** [comment]
Thanks @cunnie 
Mostly I am curious to see if it is possible and be able to use it without Internet connectivity.

It did not work though, but it looked promising :-)

sslip build with 
```
 ./sslip
2021/12/19 14:09:01 Successfully bound to all interfaces, port 53.
```
dig
`dig 127.0.0.1.myfakelocal.io +short`
curl
```
curl -v  127.0.0.1.myfakelocal.io        
* Could not resolve host: 127.0.0.1.myfakelocal.io
* Closing connection 0
curl: (6) Could not resolve host: 127.0.0.1.myfakelocal.io

```

**Comment by cunnie** [comment]
@JCzz: try forcing it to query the sslip.io DNS server by prepending `@127.0.0.1`; tell me what output you see:

```
dig @127.0.0.1 127.0.0.1.myfakelocal.io +short
```

Also, you should see log line in the output of your terminal window running the sslip.io webserver; something along the lines of the following:

```
2021/12/19 08:01:54 127.0.0.1.64162 TypeA 127.0.0.1.myfakelocal.io. ? 127.0.0.1
```

Let me know what OS you're running; judging by the output you're running on macOS, but am not sure. If you're running on macOS, `cat /etc/resolv.conf` and tell me which nameservers are being queried; you should see `nameserver 127.0.0.1` in the list.

**Comment by JCzz** [comment]
@cunnie Thanks

Adding `@127.0.0.1 ` did return
```
dig @127.0.0.1 127.0.0.1.myfakelocal.io +short
127.0.0.1
```

And there is logging
```
./sslip 
2021/12/19 17:06:47 Successfully bound to all interfaces, port 53.
2021/12/19 17:06:56 127.0.0.1.55941 TypeA 127.0.0.1.myfakelocal.io. ? 127.0.0.1
```

Yes I am running on MacOs and I added:
vi /etc/resolv.conf
`nameserver 127.0.0.1`

But still running curl on example
```
docker run -p 9090:80 -d nginxdemos/hello

 curl -v 127.0.0.1.myfakelocal.io:9090
* Could not resolve host: 127.0.0.1.myfakelocal.io
* Closing connection 0
curl: (6) Could not resolve host: 127.0.0.1.myfakelocal.io
```

**Comment by cunnie** [comment]
Aha! Set your nameserver in System Preferences → Network → Advanced → DNS → + → 127.0.0.1

`/etc/resolv.conf` is "not consulted for DNS hostname resolution, address resolution, or the DNS query routing mechanism" on macOS, or at least that's what the comment says in my `/etc/resolv.conf`

**Comment by JCzz** [comment]
Hmm, did not work.

I am running Knative on Kubernetes and it exposes services like
 `http://helloworld-go.default.127.0.0.1.sslip.io `

Thanks and let me know if you know of any other tricks.

**Comment by JCzz** [comment]
Thanks @cunnie 

Well Knative is not relevant, it was just to say it exposes services with urls like: http://helloworld-go.default.127.0.0.1.sslip.io

I will just use internet  service from sslip.io

Thanks again
