### ISSUE TITLE
How to stop dns resolution？

### ISSUE THREAD

**Issue by yongzhi-weee** [cunnie/sslip.io#16]
I want to stop this dns resolution( 139.198.158.74.sslip.io )，can you provide some help?

**Comment by cunnie** [comment]
Hi @yongzhi-weee 

Yes, please submit a pull-request. Here's the file to change: <[139.198.158.74.sslip.io](https://github.com/cunnie/sslip.io/blob/main/etc/blocklist.txt)>. Add a line at the bottom, including a reason why you want this IP address. Here's an example of the line you want to add:

```
139.198.158.74/32 # @yongzhi-weee: masquerading as Amazon https://amazon-139.198.158.74.sslip.io/login
```

As soon as you submit the PR, I'll merge it w/in a day, and the servers will pick up the change w/in an hour.

**Comment by yongzhi-weee** [comment]
Thanks for you help, The problem has been solved.
