### ISSUE TITLE
Certificate has been revoked

### ISSUE THREAD

**Issue by nallar** [cunnie/sslip.io#2]
According to [ssllabs test](https://www.ssllabs.com/ssltest/analyze.html?d=52-0-56-137.sslip.io):

![Revocation status	Revoked   INSECURE](http://i.imgur.com/8DeQPpb.png)

**Comment by ametheus** [comment]
In "[The Economics of sslip.io](http://blog.pivotal.io/labs/labs/sslip-io-a-valid-ssl-certificate-for-every-ip-address#the-economics-of-sslip-io-238-55-per-year)," did you factor in the cost of replacing wildcard certs as soon as the next internet troll figures out how to generate a revocation certificate?

**Comment by nallar** [comment]
From comment on HN ([dead] comment) by BrianCunnie:

>[Blog Author]
>As you can probably tell, Comodo revoked our certificate this morning.
>For those interested in rolling your own, we recommend getting your own wildcard certificate and >deploying your nameservers: https://github.com/cloudfoundry-community/xip-release#deploy...
>In the interim, we plan to see if there's a way we can accomplish what we want without violating the >terms of agreement.
>Thanks for the interest,

**Comment by cunnie** [comment]
Thanks @nallar — we were disappointed that our certificate was revoked, but it was a fun project to work on, and I hope the instructions we left for rolling one's own were thorough & complete.
