### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ametheus** [cunnie/sslip.io#3]
Why use HTTPS at all if you're sharing a key?

In my book, the key benefits of TLS is confidentiality, authenticity, and integrity. However, sharing a private key (a public/public key pair, if you will) basically renders those benefits moot.

So why not simply just use HTTP?

**Comment by bclozel** [comment]
This:

> sslip.io is a means for developers to test against valid SSL certificates without the bother of purchasing them.

**Comment by cunnie** [comment]
@ametheus : Yes, sharing a private key renders {confidentiality,authenticity,integrity} moot. It's for testing only.

Thanks @bclozel .
