### ISSUE TITLE
change server name returned by dns querie

### ISSUE THREAD

**Issue by avivsalman** [cunnie/sslip.io#33]
Hello,

i am tring to use this repository and deploy my own server, and when i query for some record i always get the "sslip.io" in the dns query reponse, how can i change it to my custom domain?

![image](https://github.com/cunnie/sslip.io/assets/31519121/fbdba52c-dba2-403c-b621-6d74a640c854)

Thanks, Aviv

**Comment by cunnie** [comment]
hi @avivsalman : Yup, I hard-coded the reverse-lookup: https://github.com/cunnie/sslip.io/blob/2c8a9c84a5344e0f0da60f6d8bb60f95f0290caa/src/sslip.io-dns-server/xip/xip.go#L830-L829

If you want to change it, probably introduce a new flag, `-reverse-domain=jammy.nano.io`; I'm willing to review PRs.

By the way, I have a machine whose hostname is "jammy.nono.io", so when I saw your hostnames I did a double-take.
