### ISSUE TITLE
Let's Encrypt Rate Limits

### ISSUE THREAD

**Issue by davidedc97** [cunnie/sslip.io#36]
As stated on your site at [https://sslip.io](https://sslip.io/#:~:text=2021%2D02%2D12%20Let%27s%20Encrypt%20Rate%20Limits%20If%20your%20request%20for%20an%20%22sslip.io%22%20certificate%20is%20rate%2Dlimited%2C%20please%20open%20a%20GitHub%20issue%20and%20we%27ll%20request%20a%20rate%2Dlimit%20increase.) I'm opening this issue in order for you to request a rate-limit increase. Find attached a probe of the limit. 
![image](https://github.com/cunnie/sslip.io/assets/22099548/53e07839-fc64-46f5-bb12-968a12d2c761)

**Comment by cunnie** [comment]
Thanks @davidedc97 

I've submitted a request to bump the limits. Hopefully it'll go through. Here's what they said:

> Thank you for submitting your adjustment request. Before you go:


> You must submit this form for each adjustment request. To submit this form for another adjustment, click here.

> Depending on the availability of our team, we look at form responses weekly and move the adjustments to production twice monthly. We will do our best to consider your application in a timely manner but we cannot guarantee any timeline. We’ll notify you via email when your application is processed. We reserve the right to reject applications at our discretion.

**Comment by cunnie** [comment]
Approved. From Let's Encrypt:

> Thank you for your patience as we reviewed your rate limit adjustment request(s). We have approved and deployed the following rate limit adjustment that you requested.

> Comment from the review team:

> Rate Limit Type: too many certificates already issued 

> Registration ID or Domains:   sslip.io  sslip.io  

> New Limit: 3,000 - 5,000
