### ISSUE TITLE
Send 404 response code with blocked page

### ISSUE THREAD

**Issue by Morty-Feldman** [cunnie/sslip.io#58]
I use Google's URL removal tool to help deindex mirror sites.

With the new blocked page ([example](https://128.140.77.135.sslip.io/)), doing so results in a "Denied: Page not removed" response from this tool.

Is it possible to send a 404 response code (for example, via an http header) along with this page?

If not, putting the text "404" somewhere on the page might help as Google might see that as a "soft" 404.

**Comment by cunnie** [comment]
@Morty-Feldman 404? Brilliant idea! I think I can make it work — maybe this weekend.

**Comment by cunnie** [comment]
Hi @Morty-Feldman : it should be fixed now — blocked sites return a 404 instead of a 200. Please confirm when you have the time.

**Comment by Morty-Feldman** [comment]
Looks great - awesome!
