### ISSUE TITLE
Claims any domain

### ISSUE THREAD

**Issue by NuxRo** [cunnie/sslip.io#7]
Hi,

I'm using your pipe script, however it is claiming any domain you throw at it, breaking some things.
It'll even resolve 1-2-3-4.google.com if you ask it.
Any way to limit it to only the XIP_DOMAIN?

**Comment by cunnie** [comment]
Hi Nux,

The short answer is that as the script stands it'll resolve _any_ domain, e.g. google.com. Which is what allows white-labeling (i.e. you can use any domain; you're not restricted to sslip.io)

To make it resolve _only_ the `XIP_DOMAIN`, you could take a pass at re-writing the script, or maybe check out the original scripts at xip.io.

It's possible that you're trying to use your server as both an authoritative and recursive server. That's not how it was intended; it was meant to be authoritative-only.

Good luck,

**Comment by NuxRo** [comment]
Cunnie, ok, I did not realise that's a feature..
So if I had my own domain and pointed it at your nameservers, it should work.

**Comment by cunnie** [comment]
Exactly. Check here for the how-to: https://sslip.io/#branding
