### ISSUE TITLE
Static records should only be served for the root domain

### ISSUE THREAD

**Issue by normanr** [cunnie/sslip.io#8]
Currently SOA, NS, TXT, and MX records are returned for any name, but they should probably be restricted to the root domain only.

**Comment by cunnie** [comment]
Hi @normanr ,

Help me understand how this affects you. What's the downside of returning SOA, NS, TXT, and MX records?

The server is under active development, and the behavior is fluid (I'm willing to make changes).

On another note, I'm implementing a set of changes to return a richer set of resources for the root domain "sslip.io" (especially w.r.t. TXT & MX records) and a leaner set for all other queries (no TXT, MX record pointing to itself).

**Comment by normanr** [comment]
I forget the exact reason why, I think it was just a "would be nice to have clean data" and not any breaking reason. MX records are "fixed" with 0b9ee934632b6b945390cc13a0629c742c3210a3. The discussion with respect to NS/TXT records is in #6.

**Comment by cunnie** [comment]
@normanr Thank you so much for browsing my commit history! I am impressed.

So let me ask you this: **should I remove MX records for everything _except_ the root domain sslip.io itself**? Right now I'm returning an MX record to every query pointing to itself:
```
dig +short mx 127.0.0.1.sslip.io @ns-aws.nono.io
```
returns an MX records of `127.0.0.1.sslip.io.` with a preference of zero.

**Comment by normanr** [comment]
I think the behavior as is currently implemented is fine. I opened the request back in March when the behavior of the shell script was to return protonmail records for all MX requests.
