### ISSUE TITLE
rate-limit increase

### ISSUE THREAD

**Issue by i-wintermute** [cunnie/sslip.io#80]
Please increase Let's Encrypt Rate Limits

**Comment by i-wintermute** [comment]
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for "sslip.io". Retry after 2024-10-01T18:00:00Z: see https://letsencrypt.org/docs/rate-limits/

**Comment by cunnie** [comment]
Thanks @i-wintermute for the error. Closing to consolidate with issue #57
