### ISSUE TITLE
domain 090227.xyz should update its nameserver from "ns-aws.sslip.io" to "ns-ovh.sslip.io"

### ISSUE THREAD

**Issue by cunnie** [cunnie/sslip.io#83]
Hi @cmliu

Please update your DNS nameserver for sslip.io for your domain 090227.xyz from ns-aws.sslip.io to ns-ovh.sslip.io. The AWS bandwidth costs are prohibitive, and 99% of the DNS traffic is for your domain. Thank you very much.

请将域 090227.xyz 的 sslip.io 的 DNS 名称服务器从 ns-aws.sslip.io 更新为 ns-ovh.sslip.io。 AWS 带宽成本高得令人望而却步，而且 99% 的 DNS 流量都用于您的域。非常感谢。

**Comment by cunnie** [comment]
^ @cmliu

**Comment by cmliu** [comment]
ok
