### ISSUE TITLE
[FR] Add support for hexadecimal notation

### ISSUE THREAD

**Issue by ogarcia** [cunnie/sslip.io#84]
Other similar services (such as nip.io) support hexadecimal notation for IPv4, for example:
```
01010101 -> 1.1.1.1
0b0b0b0b -> 11.11.11.11
adb3df97 -> 173.179.223.151
```

Domains of this type could be used in this way:
```
01010101.sslip.io -> 1.1.1.1
myservice.0b0b0b0b.sslip.io -> 11.11.11.11
mi-amigo-bebecafe.sslip.io -> 190.190.202.254
buy-some.deadbeef.sslip.io -> 222.173.190.239
```

It would be very interesting if sslip.io supported it as well. Also this should not conflict with IPv6 since the length of each IPv6 group is 4 hexadecimal digits and an IPv4 with this hexadecimal connotation is a group of 8.

**Comment by cunnie** [comment]
Nice idea, but I'll pass on it. I want to avoid unintentionally breaking someone who can't figure out why their sslip.io DNS resolution is suddenly returning a different IP address — it would violate the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If you want feature, I'd encourage you to use nip.io — it's a great service. And I'm not driven to have feature parity with nip.io.

**Comment by ogarcia** [comment]
> e.g. `deadbeef.127.0.0.1.sslip.io` would suddenly return an A record other than `127.0.0.1`.

But that should never happen because if you first look for an IP in the string through a regex (and find it) you resolve the IP.

Basically it would be to do all the logic that you have already implemented and if it hasn't matched anything then look for the hexadecimal string.

**Comment by cunnie** [comment]
I think you're onto something! I encourage you to fork my code, make the changes, and run the service! There has been a withering if xip.io-style services, and I think a rich & diverse ecosystem would only help.
